name: Build One Gazebo Release If Necessary

on:
  workflow_dispatch:
    inputs:
      gazebo_release:
        type: string
        description: Gazebo Release to build
        default: "harmonic"
      image_registry:
        description: The container registry to push to (must be ghcr.io)
        default: "ghcr.io/j-rivero"
        type: string
      image_name:
        description: The name of the image
        default: "gazebo"
        type: string
  workflow_call:
    inputs:
      gazebo_release:
        description: Gazebo Release to build
        type: string
        required: true
      image_registry:
        description: The container registry to push to (must be ghcr.io)
        default: "ghcr.io/j-rivero"
        type: string
      image_name:
        description: The name of the image
        default: "gazebo"
        type: string

permissions:
      packages: write
      contents: read

jobs:

  check_for_update:
    runs-on: ubuntu-latest
    container:
      image: "${{ inputs.image_registry }}/${{ inputs.image_name }}:${{ inputs.gazebo_release }}-full"
    outputs:
      needs_update: "${{ steps.do_check.outputs.needs_update }}"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
      - name: Check if update is available
        id: do_check
        run: |
          apt-get update
          result=$(./scripts/is_new_version_available.py --apt-package "gz-${{ inputs.gazebo_release }}")
          echo "${result}"
          echo "needs_update=${result}" >> "${GITHUB_OUTPUT}"

  call-build-and-deploy:
    needs: check_for_update
    if: needs.check_for_update.outputs.needs_update == 'YES'
    uses: ./.github/workflows/build-one-gazebo-release.yaml
    with:
      gazebo_release: ${{ inputs.gazebo_release }}
      image_registry: ${{ inputs.image_registry }}
      image_name: ${{ inputs.image_name }}