name: Gazebo Jetty Build If Necessary

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours.

permissions:
      packages: write
      contents: read

jobs:
  build-and-deploy-jetty:
    uses: ./.github/workflows/build-one-gazebo-release-if-necessary.yaml
    with:
      gazebo_release: jetty
